services:
  - type: web
    name: semaslim-app
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
